/**
 * MCCIA Pune AI Studio: Google Apps Script web app.
 * Creates Calendar events and Meet links and sends the Gmail emails for a booking.
 * Excel files are generated by the main app, not here.
 *
 * SETUP
 *  1. Services (+): add the "Google Calendar API" (identifier: Calendar, v3). Or push appsscript.json with clasp.
 *  2. Project Settings > Script properties:
 *       API_BASE_URL   your Vercel URL, e.g. https://mccia-connect.vercel.app   (to save the Meet link back)
 *       SHARED_SECRET  a long random string; set the same value as APPS_SCRIPT_SECRET in Vercel
 *  3. Deploy > New deployment > Web app: Execute as "Me", access "Anyone".
 *     Put the /exec URL in Settings > Apps Script URL (or VITE_APPS_SCRIPT_URL).
 *
 * The web app URL is public and this script sends mail from your Gmail, so set SHARED_SECRET:
 * with it, a request that does not carry the secret is refused.
 *
 * REQUEST  { action: 'create' | 'reschedule' | 'cancel' | 'ping', secret, ...fields }
 *   create:     ticketNumber, moduleSlug, moduleName, clientName, clientEmail, coordinatorEmail,
 *               startTime, endTime (ISO), mode ('online' | 'offline'), venueAddress, bookingId,
 *               sendConfirmation (false = do not email the client)
 *   reschedule: the create fields plus oldEventId
 *   cancel:     eventId, clientEmail, ticketNumber
 * REPLY    { success, ... }. For create: eventId, meetingLink ('' when offline), clientEmailSent.
 */

const STUDIO_NAME = 'MCCIA Pune AI Studio';
const STUDIO_ADDRESS = 'MCCIA Trade Tower, Senapati Bapat Road, Pune 411016';
const TIME_ZONE = 'Asia/Kolkata';
const MEET_ATTEMPTS = 5; // the Meet link can take a moment to appear after the event is created

function doPost(e) {
  try {
    const data = JSON.parse(e.postData.contents);
    checkSecret(data);
    switch (data.action) {
      case 'create':
        return json(createBooking(data));
      case 'reschedule':
        return json(rescheduleBooking(data));
      case 'cancel':
        return json(cancelBooking(data));
      case 'ping':
        return json({ success: true });
      default:
        return json({ success: false, error: 'Unknown action: ' + data.action });
    }
  } catch (err) {
    console.error(err);
    return json({ success: false, error: String((err && err.message) || err) });
  }
}

function checkSecret(data) {
  const secret = PropertiesService.getScriptProperties().getProperty('SHARED_SECRET');
  if (secret && data.secret !== secret) throw new Error('Not allowed');
}

function createBooking(data, requestSuffix) {
  const online = data.mode === 'online';

  // One calendar event for every booking; online ones also ask Google for a Meet conference.
  const resource = {
    summary: data.moduleName + ' - ' + data.clientName + ' | ' + data.ticketNumber,
    description: buildDescription(data),
    location: online ? '' : data.venueAddress || STUDIO_ADDRESS,
    start: { dateTime: data.startTime, timeZone: TIME_ZONE },
    end: { dateTime: data.endTime, timeZone: TIME_ZONE },
    attendees: [data.clientEmail, data.coordinatorEmail].filter(Boolean).map(function (email) {
      return { email: email };
    }),
  };
  if (online) {
    resource.conferenceData = {
      createRequest: { requestId: data.bookingId + (requestSuffix || ''), conferenceSolutionKey: { type: 'hangoutsMeet' } },
    };
  }
  const event = Calendar.Events.insert(resource, 'primary', { conferenceDataVersion: 1, sendUpdates: 'none' });

  let meetLink = online ? meetLinkOf(event) : '';
  for (let attempt = 1; online && !meetLink && attempt < MEET_ATTEMPTS; attempt++) {
    Utilities.sleep(1000);
    meetLink = meetLinkOf(Calendar.Events.get('primary', event.id));
  }

  // Save the link in the database (the web app also reads it from this reply; this covers a reply that arrives too late).
  tryTo(function () {
    writeMeetLinkBack(data.bookingId, meetLink, event.id);
  });

  const clientEmailSent = data.sendConfirmation === false ? false : tryTo(function () { sendClientConfirmation(data, meetLink); });
  if (data.coordinatorEmail) {
    tryTo(function () { sendCoordinatorNotification(data, meetLink); });
  }

  return { success: true, eventId: event.id, meetingLink: meetLink, clientEmailSent: clientEmailSent };
}

function meetLinkOf(event) {
  if (event.hangoutLink) return event.hangoutLink;
  const points = (event.conferenceData && event.conferenceData.entryPoints) || [];
  const video = points.filter(function (point) { return point.entryPointType === 'video'; })[0];
  return video ? video.uri : '';
}

/** Tells the web app the Meet link and event id (POST /api/bookings with action 'update-meet'). */
function writeMeetLinkBack(bookingId, meetLink, eventId) {
  const props = PropertiesService.getScriptProperties();
  const base = props.getProperty('API_BASE_URL');
  if (!base) return;
  const response = UrlFetchApp.fetch(base.replace(/\/+$/, '') + '/api/bookings', {
    method: 'post',
    contentType: 'application/json',
    muteHttpExceptions: true,
    payload: JSON.stringify({ action: 'update-meet', bookingId: bookingId, meetLink: meetLink, eventId: eventId, secret: props.getProperty('SHARED_SECRET') }),
  });
  if (response.getResponseCode() >= 400) console.error('Saving the Meet link failed: HTTP ' + response.getResponseCode());
}

function sendClientConfirmation(data, meetLink) {
  const subject = 'Booking Confirmed - ' + data.moduleName + ' | ' + data.ticketNumber;
  const label = 'padding:8px;color:#6b7280;';
  const where =
    data.mode === 'online'
      ? '<tr><td style="' + label + '">Meet Link</td><td style="padding:8px;">' +
        (meetLink ? '<a href="' + esc(meetLink) + '" style="color:#C41E3A;">Join Meeting</a>' : 'The link will be shared before the session.') +
        '</td></tr>'
      : '<tr><td style="' + label + '">Venue</td><td style="padding:8px;">' + esc(data.venueAddress || STUDIO_ADDRESS) + '</td></tr>';

  const body =
    '<div style="font-family:Inter,sans-serif;max-width:600px;">' +
    '<div style="background:#8B1A1A;padding:20px;text-align:center;"><h2 style="color:white;margin:0;">' + STUDIO_NAME + '</h2></div>' +
    '<div style="padding:24px;">' +
    '<p>Dear ' + esc(data.clientName) + ',</p><p>Your booking has been confirmed.</p>' +
    '<table style="width:100%;border-collapse:collapse;">' +
    '<tr><td style="' + label + '">Ticket</td><td style="padding:8px;font-weight:bold;color:#C41E3A;">' + esc(data.ticketNumber) + '</td></tr>' +
    '<tr><td style="' + label + '">Module</td><td style="padding:8px;">' + esc(data.moduleName) + '</td></tr>' +
    '<tr><td style="' + label + '">Date & Time</td><td style="padding:8px;">' + esc(whenText(data.startTime)) + '</td></tr>' +
    '<tr><td style="' + label + '">Mode</td><td style="padding:8px;">' + esc(data.mode) + '</td></tr>' +
    where +
    '</table></div>' +
    '<div style="background:#f4f6f8;padding:16px;text-align:center;font-size:12px;color:#6b7280;">' + STUDIO_ADDRESS + '</div>' +
    '</div>';

  GmailApp.sendEmail(data.clientEmail, subject, 'Your booking ' + data.ticketNumber + ' is confirmed: ' + whenText(data.startTime) + '.', { htmlBody: body, name: STUDIO_NAME });
}

function sendCoordinatorNotification(data, meetLink) {
  const lines = [
    'New booking assigned to you.',
    'Client: ' + data.clientName,
    'Ticket: ' + data.ticketNumber,
    'Module: ' + data.moduleName,
    'Time: ' + whenText(data.startTime),
    'Mode: ' + data.mode,
  ];
  if (meetLink) lines.push('Meet: ' + meetLink);
  GmailApp.sendEmail(data.coordinatorEmail, 'New Booking Assigned - ' + data.ticketNumber, lines.join('\n'), { name: STUDIO_NAME });
}

/** Replaces the old event with a new one (the new event gets its own Meet link and the client is emailed again). */
function rescheduleBooking(data) {
  if (data.oldEventId) {
    tryTo(function () { Calendar.Events.remove('primary', data.oldEventId); });
  }
  return createBooking(data, '-' + new Date().getTime());
}

function cancelBooking(data) {
  if (data.eventId) {
    tryTo(function () { Calendar.Events.remove('primary', data.eventId); });
  }
  if (data.clientEmail) {
    tryTo(function () {
      GmailApp.sendEmail(data.clientEmail, 'Booking Cancelled - ' + data.ticketNumber, 'Your booking ' + data.ticketNumber + ' has been cancelled.', { name: STUDIO_NAME });
    });
  }
  return { success: true };
}

function buildDescription(data) {
  return 'Ticket: ' + data.ticketNumber + '\nClient: ' + data.clientName + '\nMode: ' + data.mode + '\nBooked via MCCIA Pune AI Studio CRM';
}

function whenText(iso) {
  return Utilities.formatDate(new Date(iso), TIME_ZONE, 'EEEE, d MMMM yyyy, h:mm a') + ' IST';
}

/** Runs fn; a failure is logged and never stops the booking. Returns whether it worked. */
function tryTo(fn) {
  try {
    fn();
    return true;
  } catch (err) {
    console.error(err);
    return false;
  }
}

/** HTML-escapes text that came from the public booking form before it goes into an email. */
function esc(value) {
  return String(value == null ? '' : value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function json(object) {
  return ContentService.createTextOutput(JSON.stringify(object)).setMimeType(ContentService.MimeType.JSON);
}
